### Configurations for specific sources ###
sources:
  WASP-80_b_Sector-54_Exptime=20s:
    config_fn: "/WASP-80/WASP-80_b_Sector-54_Exptime=20s_Configurations_and_Results.yml"
    scripts:
      - "D_Transit_Fitting_PyTransit.py"
  WASP-80_b_Sector-54_Exptime=120s:
    config_fn: "/WASP-80/WASP-80_b_Sector-54_Exptime=120s_Configurations_and_Results.yml"
    scripts:
      - "D_Transit_Fitting_PyTransit.py"
  WASP-80_b_Sector-54_Exptime=600s:
    config_fn: "/WASP-80/WASP-80_b_Sector-54_Exptime=600s_Configurations_and_Results.yml"
    scripts:
      - "D_Transit_Fitting_PyTransit.py"


### Global settings ###
settings:
  multiprocessing: true # whether to run scripts in multiprocessing mode
  n_processes: 4 # number of processes to use in multiprocessing mode; if left blank (i.e., set to None), it will be set to min(n_sources, int(0.8 * cpu_count))
  stop_on_failure: # whether to stop the entire pipeline if a script fails; if left blank (i.e., set to None), it will be set to false
  max_retries: # Number of retries for failed script(s) after the first attempt. Set this to any number larger than 0 only when running scripts that needs Internet connection, e.g., the searching and/or downloading scripts.
               # If left blank (i.e., set to None), it will be set to 0.
  retry_delay: # seconds, delay between retries; if left blank (i.e., set to None), it will be set to 5.0